### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [fabian-hiller/Jamming#5]
(Exceeds Expectations)

Excellent job on this project! It looks like you have a solid understanding of the overall structure of the app as well as each individual component. And great job with the requests to the Spotify API, including chaining the `.then()` methods!

As a further challenge, continue to explore the Spotify API and see if you're able to add more features to this app. As you do, be sure to pay attention to the required parameters for making a request to an endpoint, and try to avoid making requests that do not meet these requirements (#1, #4). Happy coding!

**Comment by fabian-hiller** [comment]
Thank you very much 😃✌️
