### ISSUE TITLE
Summary-Feature Request.

### ISSUE THREAD

**Issue by farishkash** [fabian-hiller/Jamming#6]
Overall met expectations.

The project review is well structured and meets the goals of explaining the additional feature to be implemented.

One item I like to point out in the implementation, you can use the includes method.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

To see if the track already exists and reduce the amount of code even further.

Good Luck on your coding journey.

**Comment by fabian-hiller** [comment]
Thank you 😊
